"use client"
import React,{Suspense,lazy,useState} from "react"

import './globals.css'
import { Providers } from '@/redux/provider'
import { store } from "@/redux/store"
// import { useSelector } from "react-redux"
// export const metadata = {
//   title: 'Botnostic Credential Manager',
//   description: 'Generated by Botnostic credential Manager',
// }

export default function RootLayout({ children}) {

 
  return (
    <html lang="en">
    <body className="bg-[#EFEFEF] font-poppins flex overflow-y-hidden" >
       <div className='flex overflow-hidden w-full'>
        <Providers store={store}>
          <div className='flex flex-col  overflow-y-auto w-[100%]'>
          {children}
          </div>
          </Providers>
       </div>
      </body>
    </html>
  )
}
